### ISSUE TITLE
cant compile on ubuntu 13.04 (New Kernel)

### ISSUE THREAD

**Issue by regimantas** [energia/Energia#206]
make -C /lib/modules/3.8.0-9-generic/build M=/home/warend/kernel_patch/linux-3.0/cdcacm-0.1 modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-9-generic'
  CC [M]  /home/warend/kernel_patch/linux-3.0/cdcacm-0.1/cdcacm.o
/home/warend/kernel_patch/linux-3.0/cdcacm-0.1/cdcacm.c: In function ‘acm_tty_set_termios’:
/home/warend/kernel_patch/linux-3.0/cdcacm-0.1/cdcacm.c:761:29: error: incompatible types when initializing type ‘struct ktermios *’ using type ‘struct ktermios’
make[2]: *** [/home/warend/kernel_patch/linux-3.0/cdcacm-0.1/cdcacm.o] Error 1
make[1]: *** [_module_/home/warend/kernel_patch/linux-3.0/cdcacm-0.1] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.8.0-9-generic'
make: **\* [all] Error 2
